apiVersion: apps/v1
kind: Deployment
metadata: 
  name: docker-simple-go
spec:
  replicas: 2
  selector:
    matchLabels:
      name: docker-simple-go
  template:
    metadata:
      labels:
        name: docker-simple-go
    spec:
      containers:
      - name: application
        image: enesbek/docker-simple-go:latest
        ports:
          - containerPort: 3000  
---
apiVersion: v1
kind: Service
metadata: 
  name: docker-simple-go
spec:
  type: LoadBalancer
  selector:
    name: docker-simple-go
  ports:
  - name: http
    port: 80
    targetPort: 3000